#!/bin/bash
name="Angela" 
echo my name is $name
echo "The time and date is:"
date
echo Today is $(date '+%A')
username="Anfor35"
echo The system username is $username
age=35
echo "My age is $age."


